development: "http://192.168.10.41:8080/BIRT/frameset?__report=DeviceInfo.rptdesign"
production: "http://192.168.10.41:8080/BIRT/frameset?__report=DeviceInfo.rptdesign"
test: "http://localhost:3000/"
